# Esta é a versão da especificação do arquivo docker-compose
version: '3'

services:
  # Este será o nome do container. Você pode usar qualquer outro nome
  laravel-app:
      # O ambiente será construído a partir do Dockerfile contido neste diretório, por isso o ponto (.)
      # Poderíamos ter especificado a URL de uma imagem específica em vez disso
      build: .
      # Redireciona a porta local 8888 para a porta 80 do container
      ports:
        - "80:80"
      volumes:
        # Monta o conteúdo do diretório atual em /usr/share/nginx no container
        - ./:/var/www/html/
        - ./docker/nginx/default.conf:/etc/nginx/sites-available/default.conf
      # Especifica quais redes internas este container vai utilizar
      # O próprio Docker gerencia os hostnames dos containers
      networks:
        - app-network

# Define redes para os containers
networks:
    # Cria uma rede chamada app-network do tipo bridge para interligar os containers
    app-network:
      driver: bridge
